phase_1:
  epochs: 200
  batch_size: 512
  learning_rate_backbone: 5.0e-4
  learning_rate_anisotropy: 1.0e-4
  weight_decay: 1.0e-2
  reg_mean_weight: 0.1
  reg_smooth_weight: 0.05
  reg_scale_weight: 1.0
  gradient_clip: 5.0

phase_2:
  epochs: 150
  batch_size: 128
  diffusion_steps: 20
  beta_min: 0.1
  beta_max: 20.0
  schedule_hidden_dim: 256
  schedule_embed_dim: 128
  score_hidden_dim: 384
  kl_weight: 0.05
  patch_size: 8
  gamma: 0.95
  reward_weights:
    safety: 0.1
    comfort: 0.02
    progress: 1.0
  learning_rate_policies: 1.0e-4
  weight_decay: 1.0e-2
  gradient_clip: 1.0

inference:
  diffusion_steps: 20
  deterministic: true
